name: Sparrow CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  validate_code: # job id
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v2
      - name: Checkout note-c
        run: rm -rf note-c && git clone https://github.com/blues/note-c
      - name: Build in Container
        id: build
        uses: ./.github/actions/build

